version: '3'
services:
  condo-service:
    container_name: condo-service
    build: ./src/condo-service
    ports:
      - "3000:3000"
    volumes:
      - './src/condo-service:/app'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: exit 0
